[tools]
"npm:@modelcontextprotocol/inspector" = { version = "2.4.0", trust_policy_excludes = [
  "pino@9.14.0",
] }
go = "1.27.0"
goreleaser = "2.18.0"
task = "3.53.1"
golangci-lint = "2.13.2"
node = "25"
